const listProductionDummyData = [
  {
    id: 1,
    title: "IPhone 1 ",
    description: "good best 1",
    status: true,
    price: 1,
    stock: 1,
  },
  {
    id: 2,
    title: "IPhone 2",
    description: "good best 1",
    status: true,
    price: 1,
    stock: 1,
  },
  {
    id: 3,
    title: "IPhone 3",
    description: "good best 1",
    status: true,
    price: 1,
    stock: 1,
  },
  {
    id: 4,
    title: "IPhone 14",
    description: "good best 1",
    status: true,
    price: 1,
    stock: 1,
  },
  {
    id: 5,
    title: "IPhone 4",
    description: "good best 1",
    status: true,
    price: 1,
    stock: 1,
  },
  {
    id: 6,
    title: "IPhone 1",
    description: "good best 1",
    status: true,
    price: 1,
    stock: 1,
  },
  {
    id: 7,
    title: "IPhone 1",
    description: "good best 1",
    status: true,
    price: 1,
    stock: 1,
  },
  {
    id: 8,
    title: "IPhone 1",
    description: "good best 1",
    status: true,
    price: 1,
    stock: 1,
  },
  {
    id: 9,
    title: "IPhone 1",
    description: "good best 1",
    status: true,
    price: 1,
    stock: 1,
  },
  {
    id: 10,
    title: "IPhone 1",
    description: "good best 1",
    status: true,
    price: 1,
    stock: 1,
  },
  {
    id: 12,
    title: "IPhone 1",
    description: "good best 1",
    status: true,
    price: 1,
    stock: 1,
  },
  {
    id: 13,
    title: "IPhone 1",
    description: "good best 1",
    status: true,
    price: 1,
    stock: 1,
  },
];
export {listProductionDummyData}
